repos:
  - repo: local
    hooks:
      - id: update_issue_templates
        name: Update Issue Templates
        entry: script/run-in-env.sh python3 -m scripts.update_issue_templates
        pass_filenames: false
        language: script
        types: [text]
        files: ^(cdpctl/validation/.+/issue_templates\.yml)$
  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black
        args: [--safe, --quiet, --target-version, py36]
  - repo: https://github.com/asottile/blacken-docs
    rev: v1.8.0
    hooks:
      - id: blacken-docs
        additional_dependencies: [black==20.8b1]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-merge-conflict
      - id: debug-statements
      - id: check-docstring-first
      - id: check-json
        exclude: ^.vscode/
      - id: check-yaml
      - id: requirements-txt-fixer
      - id: check-byte-order-marker
      - id: check-case-conflict
      - id: fix-encoding-pragma
        args: ["--remove"]
      - id: check-ast
      - id: detect-private-key
      - id: forbid-new-submodules
  - repo: https://github.com/pre-commit/pre-commit
    rev: v2.7.0
    hooks:
      - id: validate_manifest
  - repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.5.4
    hooks:
      - id: autopep8
  - repo: https://github.com/PyCQA/isort
    rev: 5.5.0
    hooks:
      - id: isort
  - repo: https://github.com/pycqa/pylint
    rev: v2.8.2
    hooks:
      - id: pylint
  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: v0.782
  #   hooks:
  #     - id: mypy
  #       exclude: tests
  - repo: https://github.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        additional_dependencies: ["flake8-docstrings"]
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.24.2
    hooks:
      - id: yamllint
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.7.2
    hooks:
      - id: pyupgrade
        args: [--py36-plus]
exclude: "^.github/.*"
