
FROM ghcr.io/cloudera-labs/cldr-runner:full-latest

SHELL ["/bin/bash", "-o", "pipefail", "-c"]

RUN \
    yum install -y yum-utils \
    && yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo \
    && yum install -y docker-ce-cli make \
    && /usr/bin/env git clone https://github.com/cloudera-labs/cloudera-deploy.git /opt/cloudera-deploy

WORKDIR /workspaces

# Install Python dependencies from requirements
COPY requirements.txt requirements_test.txt requirements_dev.txt ./
RUN pip3 install --ignore-installed -r requirements_test.txt -r requirements.txt -r requirements_dev.txt

# Set the default shell to bash instead of sh
ENV SHELL /bin/bash
